apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9rdXNoYWxyYW8xMDM6ZVpnTEFSUjFwMnhTR2ZHVUBjbHVzdGVyMC4xYTNpcS5tb25nb2RiLm5ldC9lY29tbWVyY2Vfb3JkZXJz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: noizy23yo/e-commerce:order-service
          ports:
            - containerPort: 3004
          env:
            - name: PORT
              value: "3004"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: MONGODB_URI
            - name: CART_SERVICE_URL
              value: "http://cart-service:3003"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:3002"
            - name: USER_SERVICE_URL
              value: "http://user-service:3001"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 3004
      targetPort: 3004
