apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  PORT: "3004"
  MONGODB_URI: "mongodb+srv://munisheak:r2V7267uMR1qUvRt@munish-travel-mem.sz1p7kc.mongodb.net/ecommerce_orders"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: munisekar/order-service:latest
          ports:
            - containerPort: 3004
          envFrom:
            - configMapRef:
                name: order-service-config
          env:
            - name: CART_SERVICE_URL
              value: "http://cart-service:3003"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:3002"
            - name: USER_SERVICE_URL
              value: "http://user-service:3001"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 3004
      targetPort: 3004
