apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9rdXNoYWxyYW8xMDM6ZVpnTEFSUjFwMnhTR2ZHVUBjbHVzdGVyMC4xYTNpcS5tb25nb2RiLm5ldC9lY29tbWVyY2VfcHJvZHVjdHM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: noizy23yo/e-commerce:product-service
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: product-service-secret
                  key: MONGODB_URI
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - port: 3002
      targetPort: 3002
