apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9rdXNoYWxyYW8xMDM6ZVpnTEFSUjFwMnhTR2ZHVUBjbHVzdGVyMC4xYTNpcS5tb25nb2RiLm5ldC9lY29tbWVyY2VfdXNlcnM=
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWtleQ==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: noizy23yo/e-commerce:user-service
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: MONGODB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 3001
      targetPort: 3001
